"""The label set of reference/workflow.md. `backlog init` makes a repository match it."""
from __future__ import annotations

STATUSES = ("proposed", "approved", "in-progress", "qa", "done", "blocked")
KINDS = ("feature", "bug", "chore", "finding", "wow", "question")
SEVERITIES = ("critical", "high", "medium", "low")

LABELS = {
    "status:proposed": ("c5def5", "Proposed; waits for the owner's scope decision"),
    "status:approved": ("0e8a16", "Approved; ready for development"),
    "status:in-progress": ("fbca04", "A developer is on it"),
    "status:qa": ("5319e7", "PR open, waiting for independent QA"),
    "status:done": ("0e8a16", "Merged to dev after QA"),
    "status:blocked": ("b60205", "Waiting for the owner or an external dependency; see last comment"),
    "kind:feature": ("1d76db", "User-facing capability"),
    "kind:bug": ("d73a4a", "Defect"),
    "kind:chore": ("cfd3d7", "Maintenance, infra, tooling"),
    "kind:finding": ("e99695", "QA / security / UX finding"),
    "kind:wow": ("f9a8d4", "Delight proposal for the demo"),
    "kind:question": ("d876e3", "Question or approval request for the owner"),
    "sev:critical": ("b60205", "P0: exploitable, data loss, core flow broken for all"),
    "sev:high": ("d93f0b", "P1: serious; blocks release if security or UX blocker"),
    "sev:medium": ("fbca04", "Next sprint; shown at the demo"),
    "sev:low": ("c2e0c6", "Backlog"),
    "tier:light": ("c2e0c6", "Architect's sizing: local change on an existing pattern (Sonnet developer)"),
    "tier:standard": ("fef2c0", "Architect's sizing: a typical feature slice (Opus developer)"),
    "tier:heavy": ("d93f0b", "Architect's sizing: cross-cutting or hard (Fable developer; Opus if security)"),
    "review-failed": ("fbca04", "A review round already failed once; the next failure raises the tier"),
    "tier-up": ("d93f0b", "Two review rounds failed: developed one tier higher"),
    "complexity:high": ("5319e7", "Needs the architect's implementation note before development"),
    "needs-design": ("bfdadc", "Needs an approved design before development"),
    "design:awaiting-approval": ("fef2c0", "Design link sent to the owner"),
    "design:approved": ("0e8a16", "Owner approved the design"),
    "security": ("b60205", "Security-relevant"),
    "ux-blocker": ("b60205", "Core flow cannot be completed / data loss / a11y blocker"),
    "release-blocker": ("000000", "Release is no-go while open"),
    "architect-note": ("5319e7", "The architect's implementation note is on the issue"),
    "qa:changes-requested": ("d93f0b", "A reviewer (QA, code review or security) asked for changes on the open PR"),
    "ux-spec": ("bfdadc", "The UX spec and wireframe are on the issue; the UI design builds on them"),
    "needs:local": ("fef2c0", "Needs a local machine (e.g. a Mac) — cloud runs skip it"),
    "needs:owner": ("fef2c0", "Needs the owner: a payment, an account, a decision — cloud runs skip it"),
    "in-production": ("b60205", "The defect is live in production: hotfix path"),
    "foundation": ("0b1f33", "Foundation work (architecture, tokens, UI kit, CI) before features"),
    "signature-moment": ("f9a8d4", "One of the product's 1-3 signature moments"),
    "team:run-log": ("ededed", "Team run log (one issue per repository)"),
    "team:paused": ("b60205", "Team runs paused; owner comments /resume to continue"),
    "owner:money": ("d876e3", "Owner decision: spending"),
    "owner:scope": ("d876e3", "Owner decision: what the product does"),
    "owner:release": ("d876e3", "Owner decision: release go / no-go"),
    "owner:access": ("d876e3", "Owner decision: accounts, secrets, permissions"),
    "owner:legal": ("d876e3", "Owner decision: legal exposure"),
    "owner:design": ("d876e3", "Owner decision: design approval"),
    "team-decided": ("c2e0c6", "Decided by the team under the decision policy; the owner can reverse it"),
    "team:inbox": ("0052cc", "The owner's single to-do list, rewritten by every run"),
    "team:guard": ("b60205", "A branch-guard alert: a change reached a protected branch without a PR"),
    "team:demo": ("0052cc", "Sprint demo and release decision"),
}
