"""What `vendor` copies into a product repository and how, kept pure enough to test."""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Dict, List, Tuple

PLUGIN_REPO = "https://github.com/geeera/product-team-plugin"
HOME = ".claude/product-team"
MANIFEST = f"{HOME}/MANIFEST.json"
NOTICE = ("<!-- Generated by the product-team plugin ({version}). Do not edit here: change it in "
          "https://github.com/geeera/product-team-plugin and let self-update bring it in. -->")
SKIP_PARTS = {"__pycache__", ".DS_Store"}

# source subtree -> (destination, rewrite markdown?)
TREES = (
    ("agents", ".claude/agents", True),
    ("skills", ".claude/skills", True),
    ("scripts", f"{HOME}/scripts", False),
    ("reference", f"{HOME}/reference", True),
    ("templates", f"{HOME}/templates", True),
)
FILES = ((".claude-plugin/plugin.json", f"{HOME}/.claude-plugin/plugin.json"),
         ("CHANGELOG.md", f"{HOME}/CHANGELOG.md"), ("LICENSE", f"{HOME}/LICENSE"))


def plan(src: Path) -> Dict[str, Tuple[Path, bool]]:
    out: Dict[str, Tuple[Path, bool]] = {}
    for tree, dest, rewrite_md in TREES:
        for path in sorted((src / tree).rglob("*")):
            if path.is_dir() or SKIP_PARTS & set(path.parts) or path.suffix == ".pyc":
                continue
            rel = f"{dest}/{path.relative_to(src / tree).as_posix()}"
            out[rel] = (path, rewrite_md and path.suffix == ".md")
    for source, dest in FILES:
        if (src / source).exists():
            out[dest] = (src / source, False)
    return out


def rewrite(text: str, rel: str, version: str = "") -> str:
    text = text.replace("${CLAUDE_PLUGIN_ROOT}", HOME)
    # As project skills they are /slot-pm, not /product-team:slot-pm.
    text = text.replace("/product-team:", "/")
    if rel.startswith((".claude/agents/", ".claude/skills/")) and text.startswith("---\n"):
        end = text.index("\n---", 4) + len("\n---")
        text = text[:end] + "\n" + NOTICE.format(version=version or "see MANIFEST.json") + text[end:]
    return text


def render(src: Path, version: str) -> Dict[str, bytes]:
    """Every generated file's exact bytes for this plugin checkout — what `vendor install` writes."""
    out: Dict[str, bytes] = {}
    for rel, (source, rewrite_md) in plan(src).items():
        data = source.read_bytes()
        out[rel] = rewrite(data.decode("utf-8"), rel, version).encode("utf-8") if rewrite_md else data
    return out


def modes(src: Path) -> Dict[str, str]:
    """The git file mode each generated file gets (the manifest is a plain file)."""
    out = {rel: git_mode(source) for rel, (source, _) in plan(src).items()}
    out[MANIFEST] = "100644"
    return out


def manifest_bytes(version: str, commit: str, files: Dict[str, bytes]) -> bytes:
    manifest = {"version": version, "commit": commit,
                "files": {rel: hashlib.sha256(data).hexdigest() for rel, data in sorted(files.items())}}
    return (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")


# The self-update PR may touch these and nothing else; settings (hooks, permissions) never.
NEVER_VENDORED = re.compile(r"(^|/)\.claude/settings[^/]*\.json$")


def git_blob_sha(data: bytes) -> str:
    """The object id git gives these bytes, so a tree entry can be compared without trusting any API."""
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def git_mode(source: Path) -> str:
    return "100755" if source.stat().st_mode & 0o111 else "100644"


def parse_version(text: str) -> tuple:
    parts = text.strip().split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        raise ValueError(f"not a release version: {text!r}")
    return tuple(int(p) for p in parts)


def parse_diff_tree(raw: bytes) -> List[dict]:
    """`git diff-tree -r --no-renames -z A B` → [{status, path, mode, blob}] (mode/blob of the new side)."""
    fields = raw.split(b"\0")
    out, i = [], 0
    while i + 1 < len(fields) and fields[i].startswith(b":"):
        _old_mode, new_mode, _old_blob, new_blob, status = fields[i][1:].decode().split(" ")
        out.append({"status": status[0], "path": fields[i + 1].decode("utf-8", "surrogateescape"),
                    "mode": new_mode, "blob": new_blob})
        i += 2
    if any(fields[i:]):  # an unparsed record would otherwise go unchecked
        raise ValueError(f"unexpected git diff-tree output near field {i}")
    return out


def verify_tree(entries: List[dict], expected: Dict[str, bytes], modes: Dict[str, str], before: set) -> List[str]:
    """entries: the PR's own changes from `git diff-tree -r --no-renames` (status, path, mode, blob).

    A change is accepted only when it is exactly what the release generates: same blob, same mode, a regular
    file (no symlinks), never settings. Paths only the old install had may only be deleted.
    """
    problems = []
    for e in entries:
        path = e["path"]
        if NEVER_VENDORED.search(path):
            problems.append(f"{path}: settings are never part of a plugin update")
        elif e["status"] == "D":
            if path in expected:
                problems.append(f"{path}: deleted, but the release ships it")
            elif path not in before:
                problems.append(f"{path}: deletes a file the plugin never installed")
        elif path not in expected:
            problems.append(f"{path}: not a file this release generates")
        elif e["mode"] != modes[path]:
            problems.append(f"{path}: mode {e['mode']}, the release has {modes[path]}")
        elif e["blob"] != git_blob_sha(expected[path]):
            problems.append(f"{path}: content differs from the release")
    return problems


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_manifest(target: Path) -> dict:
    path = target / MANIFEST
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except ValueError:
        return {}


def write_manifest(target: Path, manifest: dict) -> None:
    path = target / MANIFEST
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def conflicts(target: Path, planned: Dict[str, Tuple[Path, bool]], installed: dict) -> List[str]:
    """Existing files the plugin would overwrite but never wrote: the project's own agents or skills."""
    owned = set(installed.get("files", {}))
    return sorted(rel for rel in planned if rel not in owned and (target / rel).exists())


def local_edits(target: Path, installed: dict) -> List[str]:
    """Generated files someone changed by hand since the last install (they will be overwritten)."""
    return sorted(rel for rel, digest in installed.get("files", {}).items()
                  if (target / rel).exists() and sha(target / rel) != digest)
